version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=notes
      - DB_USERNAME=root
      - DB_PASSWORD=xx123456
    depends_on:
      - db

  python_service:
    build: ./python_service
    ports:
      - "5000:5000"
    volumes:
      - ./python_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 1G

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=notes
      - MYSQL_ROOT_PASSWORD=xx123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 